---
abstract: 'Syntax sugar for setting the status and returning a response'
author:
  - 'Naveed Massjouni <naveedm9@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Res
requires:
  Dancer: 0
resources:
  bugtracker: https://github.com/ironcamel/Dancer-Plugin-Res/issues
  repository: git://github.com/ironcamel/Dancer-Plugin-Res.git
version: 0.0003
